# Generated by Django 5.0.7 on 2024-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_created_team_modified_teammembership_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="season",
            options={
                "ordering": ["start_date"],
                "verbose_name": "season",
                "verbose_name_plural": "seasons",
            },
        ),
        migrations.AddField(
            model_name="season",
            name="end_date",
            field=models.DateField(default="2024-01-01", verbose_name="end date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="start_date",
            field=models.DateField(default="2024-01-01", verbose_name="start date"),
            preserve_default=False,
        ),
    ]
