# Generated by Django 5.0.7 on 2024-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_season_options_season_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="numberpool",
            options={
                "verbose_name": "number pool",
                "verbose_name_plural": "number pools",
            },
        ),
        migrations.AddField(
            model_name="numberpool",
            name="name",
            field=models.CharField(
                default="test", max_length=250, unique=True, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
