# Generated by Django 5.0.7 on 2024-08-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_member_emergency_phone_primary"),
        ("teams", "0006_team_members_team_name_team_short_name_team_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "team", "verbose_name_plural": "teams"},
        ),
        migrations.AlterModelOptions(
            name="teammembership",
            options={
                "verbose_name": "team membership",
                "verbose_name_plural": "team memberships",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="number_pool",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="teams.numberpool",
                verbose_name="number pool",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammembership",
            name="assistant_captain",
            field=models.BooleanField(default=False, verbose_name="assistant captain"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="captain",
            field=models.BooleanField(default=False, verbose_name="captain"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="number",
            field=models.IntegerField(blank=True, null=True, verbose_name="number"),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="teams.teamrole",
                verbose_name="role",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammembership",
            name="season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="teams.season",
                verbose_name="season",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
                verbose_name="member",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
                verbose_name="team",
            ),
        ),
    ]
