# Generated by Django 5.0.7 on 2024-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_member_emergency_phone_primary"),
        ("teams", "0007_alter_team_options_alter_teammembership_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberpool",
            name="enforce_unique",
            field=models.BooleanField(
                default=True,
                help_text="If selected will enforce unique numbers on all players",
                verbose_name="enforce unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("number__gte", 0), ("number__lte", 99), _connector="OR"
                ),
                name="number_0-99",
                violation_error_message="Number must be between 0 and 99",
            ),
        ),
    ]
