# Generated by Django 5.0.7 on 2024-08-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_member_emergency_phone_primary"),
        ("teams", "0008_numberpool_enforce_unique_teammembership_number_0_99"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "season", "number"),
                name="team_season_number_unique",
                violation_error_message="Number already in use for this team in the current season",
            ),
        ),
    ]
