# Generated by Django 5.0.7 on 2024-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_alter_teampicture_options_teampicture_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="assistant_captain",
            field=models.BooleanField(
                default=False,
                help_text="Mark as assistant team captain",
                verbose_name="assistant captain",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="captain",
            field=models.BooleanField(
                default=False, help_text="Mark as team captain", verbose_name="captain"
            ),
        ),
    ]
