# Generated by Django 5.0.7 on 2024-08-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_alter_teammembership_assistant_captain_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammembership",
            options={
                "ordering": [
                    "team__name",
                    "role__sort_order",
                    "number",
                    "member__user__last_name",
                    "member__user__first_name",
                ],
                "verbose_name": "team membership",
                "verbose_name_plural": "team memberships",
            },
        ),
    ]
