# Generated by Django 5.0.7 on 2024-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_alter_teammembership_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(
                default="dummy", upload_to="team/logo/", verbose_name="logo"
            ),
            preserve_default=False,
        ),
    ]
