# Generated by Django 5.0.7 on 2024-09-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0014_team_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["name"],
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
    ]
