# Generated by Django 5.1.1 on 2024-09-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_alter_team_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="number_pool",
            field=models.ForeignKey(
                default="default",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="teams.numberpool",
                to_field="name",
                verbose_name="number pool",
            ),
        ),
    ]
