[tool.poetry]
name = "clubmanager"
version = "0.0.1"
description = "Club Management software"
authors = ["Bernard Siebens <bernard@siebens.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.0.7"
django-phonenumber-field = {extras = ["phonenumbers"], version = "^8.0.0"}
django-auditlog = "^3.0.0"
django-compressor = "^4.5.1"
django-initials-avatar = "^0.0.7"
django-extensions = "^3.2.3"
django-filter = "^24.3"
django-debug-toolbar = "^4.4.6"
rules = "^3.4"
django-markdownx = "^4.0.7"
django-cleanup = "^8.1.0"
python-dateutil = "^2.9.0"

[tool.poetry.dev-dependencies]
black = "^24.4.2"
flake8-django = "^1.4"
pytest = "^8.3.2"
coverage = "^7.6.0"
pytest-django = "^4.8.0"
teamcity-messages = "^1.32"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
