# Generated by Django 5.0.7 on 2024-08-08 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsitem",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsitem",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="publish_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time on which this item should be published. Only released items will be posted.",
                verbose_name="Publish on",
            ),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="slug",
            field=models.SlugField(default="", unique=True, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsitem",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "In Review"), (2, "Released")],
                default=0,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="text",
            field=models.TextField(default="", verbose_name="text"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsitem",
            name="title",
            field=models.CharField(default="", max_length=250, verbose_name="title"),
            preserve_default=False,
        ),
    ]
