# Generated by Django 5.0.7 on 2024-08-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsitem_author_newsitem_created_newsitem_modified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsitem",
            options={"verbose_name": "news item", "verbose_name_plural": "news items"},
        ),
    ]
