# Generated by Django 5.0.7 on 2024-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_auto_20240809_1256"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Internal"), (1, "External"), (2, "Internal External")],
                default=0,
                verbose_name="type",
            ),
        ),
    ]
