# Generated by Django 5.0.7 on 2024-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_newsitem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Internal"), (1, "External"), (2, "Internal & External")],
                default=0,
                verbose_name="type",
            ),
        ),
    ]
