# Generated by Django 5.0.7 on 2024-08-12 06:23

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_newsitem_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default="slug",
                editable=False,
                populate_from=["title"],
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
    ]
