# Generated by Django 5.0.7 on 2024-08-12 06:42

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_newsitem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="text",
            field=markdownx.models.MarkdownxField(verbose_name="text"),
        ),
    ]
