# Generated by Django 5.0.7 on 2024-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_picture_picture_news_item_main_picture_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="main_picture",
            field=models.BooleanField(
                default=False,
                help_text="The main picture is the picture shown on the cover of the news item.",
                verbose_name="main picture",
            ),
        ),
    ]
