# Generated by Django 5.0.7 on 2024-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_alter_picture_main_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsitem",
            options={
                "ordering": ["-created"],
                "verbose_name": "news item",
                "verbose_name_plural": "news items",
            },
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Internal"), (1, "External"), (2, "Internal & External")],
                default=0,
                help_text="Internal news is only visible to members after logging in. External news will be published on the website.",
                verbose_name="type",
            ),
        ),
    ]
