# Generated by Django 5.0.7 on 2024-08-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_alter_newsitem_options_alter_newsitem_type"),
        ("teams", "0012_alter_teammembership_assistant_captain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="teams",
            field=models.ManyToManyField(related_name="news_items", to="teams.team"),
        ),
    ]
