# Generated by Django 5.0.7 on 2024-09-02 07:25

from django.db import migrations


def create_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    try:
        Group.objects.create(name="admin")

    except:
        pass


def remove_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    if Group.objects.get(name="admin").exists():
        Group.objects.get(name="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_newsitem_teams"),
    ]

    operations = [migrations.RunPython(create_admin_group, remove_admin_group)]
