# Generated by Django 5.0.7 on 2024-08-30 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        ("teams", "0013_alter_teammembership_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opponent",
            options={
                "ordering": ["name"],
                "verbose_name": "opponent",
                "verbose_name_plural": "opponents",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        default="Ice Skating Center Mechelen",
                        max_length=250,
                        verbose_name="location",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="activities.opponent",
                        verbose_name="opponent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "game",
                "verbose_name_plural": "games",
                "ordering": ["-date"],
            },
        ),
    ]
