# Generated by Django 5.0.7 on 2024-09-01 13:00

import django.db.models.deletion
import teams.models
from django.db import migrations, models

import datetime


def create_default_season(apps, schema_editor):
    Season = apps.get_model("teams", "Season")

    today = datetime.date.today()
    start_year = today.year

    if today.month < 9:
        start_year = start_year - 1

    start_date = datetime.date(day=1, month=9, year=start_year)
    end_date = datetime.date(day=1, month=9, year=start_year + 1) - datetime.timedelta(days=1)

    Season.objects.create(start_date=start_date, end_date=end_date)


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_opponent_options_game"),
        ("teams", "0013_alter_teammembership_options"),
    ]

    operations = [
        migrations.RunPython(create_default_season),
        migrations.AddField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                default=teams.models.Season.get_season_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="teams.season",
                verbose_name="season",
            ),
        ),
    ]
