# Generated by Django 5.0.7 on 2024-09-01 13:00

import django.db.models.deletion
import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_opponent_options_game"),
        ("teams", "0013_alter_teammembership_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                default=teams.models.Season.get_season_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="teams.season",
                verbose_name="season",
            ),
        ),
    ]
