# Generated by Django 5.0.7 on 2024-09-01 15:20

import django.db.models.deletion
import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_game_season"),
        ("teams", "0014_team_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["date"],
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
        migrations.AlterField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                blank=True,
                default=teams.models.Season.get_season_id,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="teams.season",
                verbose_name="season",
            ),
        ),
    ]
