# Generated by Django 5.1.1 on 2024-09-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_game_live_game_score_opponent_game_score_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_id",
            field=models.CharField(
                default=123456, max_length=250, verbose_name="game_id"
            ),
            preserve_default=False,
        ),
    ]
