# Generated by Django 5.1.1 on 2024-09-07 20:31

from django.db import migrations


def create_competiton_group(apps, schema_editor):
    Competition = apps.get_model("activities", "Competition")

    try:
        Competition.objects.create(name="RBIHF", module="activities.competition.hockey")

    except:
        pass


def remove_competiton_group(apps, schema_editor):
    Competition = apps.get_model("activities", "Competition")

    try:
        Competition.objects.get(name="RBIHF", module="activities.competition.hockey").delete()

    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_game_game_id"),
    ]

    operations = [migrations.RunPython(create_competiton_group, remove_competiton_group)]
