# Generated by Django 5.1.1 on 2024-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0010_alter_game_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="score_opponent",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="score opponent"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="score_team",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="score team"
            ),
        ),
    ]
