# Generated by Django 5.1.1 on 2024-09-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0011_alter_game_score_opponent_alter_game_score_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="friendly_game",
            field=models.BooleanField(default=False, verbose_name="friendly game"),
        ),
    ]
