# Generated by Django 5.1.1 on 2024-09-23 20:18

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_game_friendly_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "game type",
                "verbose_name_plural": "game types",
                "ordering": ["name"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="game",
            name="friendly_game",
        ),
        migrations.AlterField(
            model_name="game",
            name="opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="activities.opponent",
                verbose_name="opponent",
            ),
        ),
    ]
