# Generated by Django 5.1.1 on 2024-09-23 20:19

from django.db import migrations


def create_default_game_types(apps, schema_editor):
    GameType = apps.get_model("activities", "GameType")

    try:
        GameType.objects.create(name="Friendly Game")
        GameType.objects.create(name="Competition Game")
        GameType.objects.create(name="Tournament")

    except:
        pass


def remove_default_game_types(apps, schema_editor):
    GameType = apps.get_model("activities", "GameType")

    try:
        GameType.objects.get(name="Friendly Game").delete()
        GameType.objects.get(name="Competition Game").delete()
        GameType.objects.get(name="Tournament").delete()

    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0013_gametype_remove_game_friendly_game_and_more"),
    ]

    operations = [migrations.RunPython(create_default_game_types, remove_default_game_types)]
