# Generated by Django 5.1.1 on 2024-09-23 20:22

import django.db.models.deletion
from django.db import migrations, models


def update_default_game_type(apps, schema_editor):
    GameType = apps.get_model("activities", "GameType")
    Game = apps.get_model("activities", "Game")

    default_type = GameType.objects.get(name="Competition Game")

    for game in Game.objects.all():
        game.game_type = default_type
        game.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0014_auto_20240923_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="activities.gametype",
                verbose_name="game type",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(update_default_game_type, reverse_func),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="activities.gametype",
                verbose_name="game type",
            ),
        ),
    ]
