# Generated by Django 5.1.1 on 2024-10-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0017_alter_game_competition_alter_game_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Competition",
        ),
    ]
