# Generated by Django 5.1.1 on 2024-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0019_alter_gametype_opponent_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="competition",
            field=models.CharField(
                blank=True,
                choices=[("RBIHF", "RBIHF"), ("CEHL", "CEHL")],
                max_length=20,
                null=True,
                verbose_name="competition",
            ),
        ),
    ]
