#  Copyright (c) 2024. https://github.com/bsiebens/ClubManager

# Generated by Django 5.1.1 on 2024-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0020_alter_game_competition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="competition",
            field=models.CharField(blank=True, choices=[("RBIHF", "RBIHF"), ("CEHL", "CEHL")], default="", max_length=20, verbose_name="competition"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="game_id",
            field=models.CharField(blank=True, default="", max_length=250, verbose_name="game ID"),
            preserve_default=False,
        ),
    ]
