# Generated by Django 5.0.7 on 2024-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_sponsor_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Logo will no longer be visible as of this date, leave empty to display indefinitly",
                null=True,
                verbose_name="end date",
            ),
        ),
    ]
