# Generated by Django 5.1.1 on 2024-10-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_invoice_material_lineitem"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Invoice",
            new_name="Order",
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["description"],
                "verbose_name": "material",
                "verbose_name_plural": "materials",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="invoice",
        ),
        migrations.AddField(
            model_name="lineitem",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.order",
                verbose_name="order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="material",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Select a role for which a price should be added.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.teamrole",
                verbose_name="team role",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Select a team for which a price should be added.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
                verbose_name="team",
            ),
        ),
    ]
