# Generated by Django 5.1.1 on 2024-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_rename_invoice_order_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="number",
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
