# Generated by Django 5.1.1 on 2024-10-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_lineitem_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineitem",
            options={
                "ordering": ["number"],
                "verbose_name": "line item",
                "verbose_name_plural": "line items",
            },
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="number",
            field=models.IntegerField(default=10),
        ),
    ]
