# Generated by Django 5.1.1 on 2024-10-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_lineitem_options_alter_lineitem_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="number",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
