# Generated by Django 5.1.1 on 2024-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_alter_lineitem_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
