# Generated by Django 5.1.1 on 2024-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_alter_lineitem_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="role",
        ),
        migrations.RemoveField(
            model_name="material",
            name="team",
        ),
        migrations.RemoveField(
            model_name="order",
            name="season",
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Logo will no longer be visible as of this date, leave empty to display indefinitely",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.DeleteModel(
            name="LineItem",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
