#  Copyright (c) 2024. https://github.com/bsiebens/ClubManager

# Generated by Django 5.1.1 on 2024-10-29 17:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_item"),
        ("members", "0033_remove_lineitem_invoice_remove_lineitem_material_and_more"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date on which this form becomes available",
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Final due data for this form, standard will be 30 days from the start date",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "allow_only_one_per_member",
                    models.BooleanField(
                        default=False,
                        help_text="Select to allow only one form to be submitted by each user",
                        verbose_name="one per user",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "order form",
                "verbose_name_plural": "order forms",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Submitted"),
                            (2, "Invoiced"),
                            (3, "Payed"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="members.member",
                        verbose_name="member",
                    ),
                ),
                (
                    "order_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="finance.orderform",
                        verbose_name="order form",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderFormItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="price"
                    ),
                ),
                (
                    "unit_price_type",
                    models.IntegerField(
                        choices=[(0, "amount"), (1, "percentage")],
                        default=0,
                        verbose_name="price type",
                    ),
                ),
                (
                    "member_required",
                    models.BooleanField(
                        default=False,
                        help_text="Select if this item requires a member to be associated with it when creating an order",
                        verbose_name="member required",
                    ),
                ),
                (
                    "order_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.orderform",
                        verbose_name="order form",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional, select a role for which an item should be created",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.teamrole",
                        verbose_name="team role",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional, select a team for which an item should be created",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                        verbose_name="member",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineitems",
                        to="finance.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "order_form_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineitems",
                        to="finance.orderformitem",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "line item",
                "verbose_name_plural": "line items",
                "ordering": ["number"],
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
