#  Copyright (c) 2024. https://github.com/bsiebens/ClubManager

# Generated by Django 5.1.1 on 2024-10-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_orderform_order_orderformitem_lineitem_delete_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderformitem",
            name="unit_price_type",
            field=models.IntegerField(
                choices=[(0, "amount"), (1, "percentage")],
                default=0,
                verbose_name="type",
            ),
        ),
    ]
