#  Copyright (c) 2024. https://github.com/bsiebens/ClubManager

# Generated by Django 5.1.1 on 2024-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_alter_orderformitem_unit_price_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderformitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=250, verbose_name="description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
