# Generated by Django 5.0.7 on 2024-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(default="test", upload_to="sponsors/logo/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sponsor",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
