# Generated by Django 5.0.7 on 2024-08-26 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_sponsor_logo_sponsor_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Logo will be visible as of this day",
                verbose_name="start date",
            ),
        ),
    ]
