# Generated by Django 5.0.7 on 2024-08-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_sponsor_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={
                "ordering": ["name"],
                "verbose_name": "sponsor",
                "verbose_name_plural": "sponsors",
            },
        ),
    ]
