# Generated by Django 5.0.7 on 2024-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "member", "verbose_name_plural": "members"},
        ),
        migrations.AddField(
            model_name="member",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
    ]
