# Generated by Django 5.0.7 on 2024-07-29 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_birth_date_member_license_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
