# Generated by Django 5.0.7 on 2024-07-29 22:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_member_created_member_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["user__last_name", "user__first_name", "user__username"],
                "verbose_name": "member",
                "verbose_name_plural": "members",
            },
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_phone_primary",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+3230000000",
                max_length=128,
                region=None,
                verbose_name="first emergency phone",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_phone_secondary",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="second emergency phone",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
    ]
