# Generated by Django 5.0.7 on 2024-07-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0005_alter_member_options_member_emergency_phone_primary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="license",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="license"
            ),
        ),
    ]
