# Generated by Django 5.0.7 on 2024-07-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_member_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="password_change_required",
            field=models.BooleanField(
                default=False,
                help_text="If flagged signals that this users will need to reset their password at the next login.",
                verbose_name="password change needed",
            ),
        ),
    ]
