# Generated by Django 5.0.7 on 2024-07-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_password_change_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name": "family", "verbose_name_plural": "families"},
        ),
        migrations.AddField(
            model_name="family",
            name="members",
            field=models.ManyToManyField(to="members.member", verbose_name="members"),
        ),
        migrations.AddField(
            model_name="family",
            name="name",
            field=models.CharField(default="test", max_length=250, verbose_name="name"),
            preserve_default=False,
        ),
    ]
