# Generated by Django 5.0.7 on 2024-07-30 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_family_options_family_members_family_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="family",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
