# Generated by Django 5.0.7 on 2024-08-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_family_created_family_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_organisation_admin",
            field=models.BooleanField(
                default=False,
                help_text="An organization admin will have advanced access rights into the system.",
                verbose_name="Organization admin",
            ),
        ),
    ]
