# Generated by Django 5.0.7 on 2024-08-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_rename_is_organisation_admin_member_is_organization_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="birth_date",
            new_name="birthday",
        ),
    ]
