# Generated by Django 5.0.7 on 2024-08-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_rename_birth_date_member_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="birthday"),
        ),
    ]
