# Generated by Django 5.1.1 on 2024-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_alter_member_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="license",
            field=models.CharField(blank=True, max_length=250, verbose_name="license"),
        ),
    ]
