# Generated by Django 5.1.1 on 2024-10-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_member_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="children",
            field=models.ManyToManyField(blank=True, to="members.member"),
        ),
    ]
