# Generated by Django 5.1.1 on 2024-10-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0019_alter_member_children"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="children",
            new_name="family_members",
        ),
    ]
