# Generated by Django 5.1.1 on 2024-10-21 20:17

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_delete_family"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (0, "New"),
                            (1, "Submitted"),
                            (2, "Invoiced"),
                            (3, "Payed"),
                        ],
                        default=0,
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
