# Generated by Django 5.1.1 on 2024-10-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_subscription"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.season",
            ),
            preserve_default=False,
        ),
    ]
