# Generated by Django 5.1.1 on 2024-10-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_subscription_season"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscription",
            new_name="Invoice",
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "invoice", "verbose_name_plural": "invoices"},
        ),
    ]
