# Generated by Django 5.1.1 on 2024-10-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0024_rename_subscription_invoice_alter_invoice_options"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.season",
                verbose_name="season",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[(0, "New"), (1, "Submitted"), (2, "Invoiced"), (3, "Payed")],
                default=0,
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
