# Generated by Django 5.1.1 on 2024-10-21 21:21

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0025_alter_invoice_season_alter_invoice_status"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="price"
                    ),
                ),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[(0, "amount"), (1, "percentage")],
                        default=0,
                        verbose_name="price type",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.teamrole",
                        verbose_name="team role",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "member invoice item",
                "verbose_name_plural": "member invoice items",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
