# Generated by Django 5.1.1 on 2024-10-21 21:32

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0026_membermaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="price"
                    ),
                ),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[(0, "amount"), (1, "percentage")],
                        default=0,
                        verbose_name="price type",
                    ),
                ),
            ],
            options={
                "verbose_name": "discount item",
                "verbose_name_plural": "discount items",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="membermaterial",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="price"
            ),
        ),
    ]
