# Generated by Django 5.1.1 on 2024-10-21 21:48

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0027_discountmaterial_alter_membermaterial_price"),
        ("teams", "0016_alter_team_number_pool"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.invoice",
                        verbose_name="invoice",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                        verbose_name="member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="price"
                    ),
                ),
                (
                    "price_type",
                    models.IntegerField(
                        choices=[(0, "amount"), (1, "percentage")],
                        default=0,
                        verbose_name="price type",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.teamrole",
                        verbose_name="team role",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
            },
        ),
        migrations.DeleteModel(
            name="DiscountMaterial",
        ),
        migrations.AddField(
            model_name="lineitem",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="members.material",
                verbose_name="item",
            ),
        ),
        migrations.DeleteModel(
            name="MemberMaterial",
        ),
    ]
