# Generated by Django 5.1.1 on 2024-10-21 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0028_lineitem_material_delete_discountmaterial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
