# Generated by Django 5.1.1 on 2024-10-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0030_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lineitem",
            options={"verbose_name": "line item", "verbose_name_plural": "line items"},
        ),
    ]
