# Generated by Django 5.1.1 on 2024-10-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0032_alter_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="material",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="member",
        ),
        migrations.RemoveField(
            model_name="material",
            name="role",
        ),
        migrations.RemoveField(
            model_name="material",
            name="team",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="LineItem",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
